"""Write CQRS commands for the support domain (Story 5.8 dispute tickets, Story 5.9 recommendation feedback).

All functions accept a psycopg ``AsyncConnection`` (from ``db.transaction()``).
Raw SQL via psycopg3 (``%s`` placeholders); no ORM.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from uuid import UUID

    from psycopg import AsyncConnection


async def log_recommendation_feedback(
    conn: AsyncConnection,
    subscriber_id: UUID,
    plan_id: UUID,
    action: str,
) -> None:
    """Insert a recommendation feedback row into segmentation_recommendation_feedback."""
    await conn.execute(
        """INSERT INTO segmentation_recommendation_feedback
               (subscriber_id, recommended_plan_id, action_taken, recommendation_type)
           VALUES (%s::uuid, %s::uuid, %s, 'PLAN_RECOMMENDATION')""",
        (str(subscriber_id), str(plan_id), action),
    )


# ── Story 5.8: billing-dispute support tickets ────────────────────────────────
# Dispute payload serialised into ``support_tickets.description``. Kept in sync
# with the decoder in ``db.support.queries`` — both modules own one direction.


def encode_dispute_description(
    cdr_reference: str,
    charge_paise: int,
    dispute_reason: str,
) -> str:
    """Serialise the dispute payload into the ``description`` column value.

    The V1 ``support_tickets`` table is a generic ticketing schema with no
    dispute-specific columns, so the values (``cdr_reference``, ``charge_paise``,
    ``dispute_reason``) are stored as JSON in ``description`` — recoverable on read
    (AC #4) without a schema change (AC #7; memory: V1 = full all-domain baseline).
    """
    return json.dumps(
        {
            "cdr_reference": cdr_reference,
            "charge_paise": charge_paise,
            "dispute_reason": dispute_reason,
        }
    )


async def create_ticket(
    conn: AsyncConnection,
    *,
    subscriber_id: str,
    cdr_reference: str,
    charge_paise: int,
    dispute_reason: str = "subscriber_initiated",
) -> dict:
    """Insert a billing-dispute support ticket and return the new row.

    ``category`` is the ticket type (``billing_dispute``); the dispute values go
    into ``description`` via :func:`encode_dispute_description`. ``status`` reuses
    the V1 default (``open``) and ``priority`` the V1 default (``medium``). The PK
    ``id`` is generated by ``uuid_generate_v7()`` server-side (architecture §1.7.1).

    Returns a dict of the stored columns: ``id`` (UUID), ``subscriber_id``,
    ``category``, ``subject``, ``description``, ``status``, ``created_at``.
    """
    description = encode_dispute_description(cdr_reference, charge_paise, dispute_reason)
    subject = f"Disputed charge: CDR {cdr_reference}"
    cur = await conn.execute(
        """
        INSERT INTO support_tickets
            (subscriber_id, category, subject, description, status, priority)
        VALUES (%s::uuid, 'billing_dispute', %s, %s, 'open', 'medium')
        RETURNING id, subscriber_id, category, subject, description, status, created_at
        """,
        (subscriber_id, subject, description),
    )
    row = await cur.fetchone()
    if row is None:
        # INSERT ... RETURNING always yields exactly one row; None indicates a
        # driver/transaction problem rather than a normal control-flow path.
        raise RuntimeError("create_ticket: INSERT ... RETURNING produced no row")
    return {
        "id": row[0],
        "subscriber_id": str(row[1]),
        "category": row[2],
        "subject": row[3],
        "description": row[4],
        "status": row[5],
        "created_at": row[6],
    }


__all__ = ["create_ticket", "encode_dispute_description", "log_recommendation_feedback"]
