receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlp/otel-tui:
    endpoint: otel-tui:4317
    tls:
      insecure: true
  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/otel-tui, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/otel-tui, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/otel-tui, debug]
