"""Pydantic request/response models for recharge endpoints (Story 3.5).

Money is always integer paise internally; INR conversion (paise / 100) happens
only at the presentation boundary (architecture §1.11.2, §1.11.3).
"""

from __future__ import annotations

from datetime import datetime  # noqa: TC003 — pydantic resolves field types at runtime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator


class RechargeRequest(BaseModel):
    """Request body for POST /api/v1/subscriber/recharge."""

    model_config = ConfigDict(extra="forbid")

    plan_id: UUID = Field(..., description="Plan to purchase (from catalogue)")
    payment_method_id: UUID = Field(..., description="Saved payment method to use")
    idempotency_key: str = Field(
        ...,
        min_length=1,
        max_length=100,
        description="Client-generated UUIDv7 for idempotency (FR-16)",
    )

    @field_validator("idempotency_key")
    @classmethod
    def validate_idempotency_key(cls, value: str) -> str:
        """Validate that idempotency_key is a valid UUID (client-generated UUIDv7)."""
        try:
            UUID(value)
        except (ValueError, TypeError, AttributeError) as exc:
            raise ValueError("idempotency_key must be a valid UUID") from exc
        return value


class RechargeResponse(BaseModel):
    """Response body for successful recharge (POST /api/v1/subscriber/recharge)."""

    model_config = ConfigDict(extra="forbid")

    transaction_id: UUID = Field(..., description="Recharge order UUID")
    new_balance_paise: int = Field(..., ge=0, description="Wallet balance after recharge")
    plan_activation_timestamp: datetime = Field(
        ...,
        description="Plan activation timestamp (subscription start_date)",
    )
    receipt_url: str = Field(..., description="URL to fetch PDF receipt (generated by Story 3.6)")


__all__ = ["RechargeRequest", "RechargeResponse"]
