-- V14: Make identity_subscribers.msisdn nullable so that the column is populated
-- only at SIM activation time (auto-generated by the simulator/activation service),
-- not at registration time where no phone number has been assigned yet.
ALTER TABLE identity_subscribers ALTER COLUMN msisdn DROP NOT NULL;
